export const projects_list = [
    {
        name: "MangaFoo",
        imageUrl: "/projects_images/mangafoo.png",
        description: "AI manga/comic creation app using Stable Diffusion.",
        skills: [
            {
                imageUrl: "/skill_icons/reacticon.svg",
                name: "React"
            },
            {
                imageUrl: "/skill_icons/fastapiicon.svg",
                name: "FastAPI"
            },
            {
                imageUrl: "/skill_icons/pytorchicon.svg",
                name: "PyTorch"
            },
            {
                imageUrl: "/skill_icons/postgresqlicon.svg",
                name: "PostgreSQL"
            },
            {
                imageUrl: "/skill_icons/awsicon.svg",
                name: "AWS"
            },
            {
                imageUrl: "/skill_icons/dockericon.svg",
                name: "Docker"
            },
            {
                imageUrl: "/skill_icons/huggingfaceicon.svg",
                name: "HuggingFace"
            },
            {
                imageUrl: "/skill_icons/chakrauiicon.svg",
                name: "ChakraUI"
            },
        ]
    },
    {
        name: "AI Roleplay Chatbot",
        imageUrl: "/projects_images/ai_roleplay_chatbot.png",
        description: "Conversational roleplay mimicking a character using OpenAI API with reactions to go along with the chat generated by Stable Diffusion.",
        skills: [
            {
                imageUrl: "/skill_icons/openaiicon.svg",
                name: "OpenAI API"
            },
            {
                imageUrl: "/skill_icons/fastapiicon.svg",
                name: "FastAPI"
            },
            {
                imageUrl: "/skill_icons/pytorchicon.svg",
                name: "PyTorch"
            },
            {
                imageUrl: "/skill_icons/huggingfaceicon.svg",
                name: "HuggingFace"
            },
        ]
    },
    {
        name: "PetPal",
        imageUrl: "/projects_images/petpal.png",
        description: "Dating app-style platform for matching pet shelters with potential adopters.",
        skills: [
            {
                imageUrl: "/skill_icons/javaicon.svg",
                name: "Java"
            },
            {
                imageUrl: "/skill_icons/mongodbicon.svg",
                name: "MongoDB"
            },
            {
                imageUrl: "/skill_icons/gcpicon.svg",
                name: "GCP"
            },
        ]
    },
    {
        name: "Leetcode Flashcards",
        imageUrl: "/projects_images/leetcode_flashcards.png",
        description: "Flashcard app for Leetcode studying.",
        skills: [
            {
                imageUrl: "/skill_icons/nodejsicon.svg",
                name: "NodeJS"
            },
            {
                imageUrl: "/skill_icons/firebaseicon.svg",
                name: "Firebase"
            },
            {
                imageUrl: "/skill_icons/reacticon.svg",
                name: "React"
            },
        ]
    },
    {
        name: "Mental Health Chatbot",
        imageUrl: "/projects_images/mental_health_chatbot.png",
        description: "Mental health chatbot based on the paper 'Attention is All You Need'.",
        skills: [
            {
                imageUrl: "/skill_icons/tensorflowicon.svg",
                name: "TensorFlow"
            },
            {
                imageUrl: "/skill_icons/pythonicon.svg",
                name: "Python"
            },
        ]
    },
    {
        name: "WakeUpAlarm",
        imageUrl: "project_images/wakeup_alarm.png",
        description: "iOS alarm and clock app.",
        skills: [
            {
                imageUrl: "/skill_icons/swifticon.svg",
                name: "Swift"
            },
            {
                imageUrl: "/skill_icons/swifticon.svg",
                name: "SwiftUI"
            }
        ]
    },
    {
        name: "Portfolio 2",
        imageUrl: "/projects_images/portfolio_2.png",
        description: "Netflix-inspired portfolio website.",
        skills: [
            {
                imageUrl: "/skill_icons/nextjsicon.svg",
                name: "NextJS"
            },
            {
                imageUrl: "/skill_icons/tsicon.svg",
                name: "Typescript"
            },
            {
                imageUrl: "/skill_icons/htmlicon.svg",
                name: "HTML"
            },
            {
                imageUrl: "/skill_icons/cssicon.svg",
                name: "CSS"
            },
            {
                imageUrl: "/skill_icons/tailwindcssicon.svg",
                name: "TailwindCSS"
            }
        ]
    },
    {
        name: "Portfolio 1",
        imageUrl: "/projects_images/portfolio_1.png",
        description: "3D scene for portfolio website.",
        skills: [
            {
                imageUrl: "/skill_icons/threejsicon.svg",
                name: "ThreeJS"
            },
            {
                imageUrl: "/skill_icons/reacticon.svg",
                name: "React"
            },
            {
                imageUrl: "/skill_icons/tailwindcssicon.svg",
                name: "TailwindCSS"
            }
        ]
    },
    {
        name: "North Shore Mountains",
        imageUrl: "/projects_images/north_shore_mountains.png",
        description: "Interactive 3D blog website about the North Shore Ski Mountains in BC.",
        skills: [
            {
                imageUrl: "/skill_icons/threejsicon.svg",
                name: "ThreeJS"
            },
            {
                imageUrl: "/skill_icons/reacticon.svg",
                name: "React"
            },
            {
                imageUrl: "/skill_icons/tailwindcssicon.svg",
                name: "TailwindCSS"
            }
        ]
    },
];
